- name: Copy /etc/resolv.conf
  copy:
    src: /etc/resolv.conf
    dest: /etc/resolv.conf_bck

- name: Create /etc/resolv.conf
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf


