### Install bind9
- name: Install bind9
  apt:
    name: bind9, bind9utils, bind9-doc, firewalld
    state: latest

##bind9 configuration

- name: Configure bind9
  template: 
    src: named.conf.j2
    dest: /etc/bind/named.conf

#### Zones configuration

- name: Asure directories exists
  file:
    path: "{{ item }}"
    state: directory
    owner: bind
    group: bind
    mode: 0750
  loop: 
    - "/etc/bind/zones"
    - "/var/log/named/"
    #- "/var/lib/named/zones"


- name: Asure directories exists
  file:
    path: /var/log/named/bind.log
    state: touch
    owner: bind
    group: bind
    mode: 0750


- name: Create named.conf.local.j2
  template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local


- name: Define direct zones
  template:
    src: db.zone.j2
    dest: /etc/bind/zones/{{ item.name }}
  loop: "{{ dns_zones }}"

- name: Define reverse zones
  template:
    src: db.reverse.j2
    dest: "/etc/bind/zones/{{ item.reverse }}.in-addr.arpa"
  loop: "{{ dns_zones }}"

- name: Open DNS port
  firewalld:
    service: dns
    permanent: true
    state: enabled

- name: Reload firewall-cmd
  command: "firewall-cmd --reload"

- name: Wait for firewall reload
  wait_for: 
    timeout: 60

- name: Start bind9
  service:
    name: bind9
    state: restarted

