### Install slapd
- name: Install slapd
  apt:
    name: debconf-utils
    state: latest
    force: yes

- name: Configure slapd
  debconf:
    name: slapd
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  loop:
    - { question: "slapd/internal/adminpw", value: "{{ ldap_admin_password }}", vtype: "password" }
    - { question: "slapd/internal/generated_adminpw", value: "{{ ldap_admin_password }}", vtype: "password" }
    - { question: "slapd/password1", value: "{{ ldap_admin_password }}", vtype: "password" }
    - { question: "slapd/password2", value: "{{ ldap_admin_password }}", vtype: "password" }
    - { question: "slapd/domain", value: "{{ ldap_domain }}", vtype: "string" }
    - { question: "slapd/organization", value: "{{ ldap_organization }}", vtype: "string" }
    - { question: "slapd/no_configuration", value: "false", vtype: "boolean" }

- name: Install slapd
  apt:
    name: slapd, ldap-utils
    state: present
    update_cache: yes
