- name: Delete vagrant access to the server
  hosts: ns1-server-1
  become: true
  gather_facts: yes
  tasks:
    - name: Edit sudoers configuration
      file:
        path: /home/vagrant/.ssh/authorized_keys
        state: absent
    - name: Delete vagrant deployment
      file:
        path: /vagrant
        state: absent
    - name: Restart sshd
      service:
        name: sshd
        state: restarted
    - name: Edit sudoers configuration
      file:
        path: /etc/sudoers.d/vagrant
        state: absent
