- name: Delete vagrant access to the server
  hosts: ns1-server-1
  become: true
  gather_facts: yes
  tasks:
    - name: Edit sudoers configuration
      file:
        path: /etc/sudoers.d/vagrant
        state: absent
    - name: Delete user vagrant
      user:
        name: vagrant
        state: absent
        remove: yes