Vagrant.configure("2") do |config|
  config.vm.box = "kalilinux/rolling"
   config.vm.hostname = "attacker"

  config.vm.provider :virtualbox do |v|
    v.name = "attacker"
    v.memory = 2048
    v.cpus = 5
  end

  config.vm.network "public_network", ip: "192.168.1.87", bridge: "Realtek PCIe GBE Family Controller"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y software-properties-common
  SHELL
end
