Vagrant.configure("2") do |config|
  # Imagen base de Ubuntu 22.04 (Jammy Jellyfish)
  config.vm.box = "ubuntu/jammy64"
   config.vm.hostname = "ns1-server-1"

  config.vm.provider :virtualbox do |v|
    v.name = "CTF"
    v.memory = 512
    v.cpus = 5
  end

  #This is the folder where all the files are going to be sync
  config.vm.synced_folder ".", "/vagrant", type: "rsync"


  # Configuración de red en modo puente
  config.vm.network "public_network", ip: "192.168.1.86", bridge: "Realtek PCIe GBE Family Controller"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y software-properties-common
    add-apt-repository --yes --update ppa:ansible/ansible
    apt-get install -y ansible
  SHELL

  
  config.vm.provision "ansible_local" do |ansible|
    ansible.inventory_path = "/vagrant/inventories/hosts"
    #ansible.verbose = 'vvv'
    ansible.playbook = "/vagrant/playbooks/deployment.yml"
    ansible.become = true
    ansible.limit = 'all' # to avoid --limit="default on ansible command
  end

end
