Vagrant.configure("2") do |config|
  # Imagen base de Ubuntu 22.04 (Jammy Jellyfish)
  config.vm.box = "ubuntu/jammy64"


  # config.vm.synced_folder ".", "/vagrant"
  
  # Configuración de red en modo puente
  config.vm.network "public_network", ip: "192.168.1.86", bridge: "Realtek PCIe GBE Family Controller"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y software-properties-common
    add-apt-repository --yes --update ppa:ansible/ansible
    apt-get install -y ansible
  SHELL
  
  # Configuración de Ansible local
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbooks/deployment.yml"
  end
end