---
- hosts: localhost
  become: yes
  tasks:
  - name: Dns servers deployment
    include_role:
      name: dns_role
      tasks_from: dns_servers.yml

  
- hosts: localhost
  become: yes
  tasks:
  - include_role:
      name: dns_role
      tasks_from: dns_clients.yml
  