### Install ftp
- name: Install ftp
  apt:
    name: vsftpd
    state: latest

- name: Add Anonymous FTP configuration
  blockinfile:
    path: /etc/vsftpd.conf
    block: |
      write_enable=YES
      anon_upload_enable=YES
      anon_root=/srv/ftp


- name: Edit vsftp configuration
  lineinfile:
    path: /etc/vsftpd.conf
    create: yes
    state: present
    regexp: "^anonymous_enable=NO\\s+"
    line: "anonymous_enable=YES"

- name: Open vsftpd port
  firewalld:
    service: ftp
    permanent: true
    state: enabled

- name: Reload firewall-cmd
  command: "firewall-cmd --reload"

- name: Start ftp
  service:
    name: vsftpd
    state: restarted

- name: Set ftp flag
  copy:
    src: anonymous_flag.txt
    dest: /srv/ftp/anonymous_flag.txt
    mode: '0644'
